project_name            = "apigee-test-334219"
gcp_credentials_path    = "~/.config/gcloud/apigee-test-334219.json"
region                  = "us-west1"
zone                    = "us-west1-a"
ssh_username            = "joey"
ssh_pub_key_path        = "~/.ssh/ansible-key"